# Generated by Django 2.1.7 on 2019-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('auther', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
