# Generated by Django 2.1.7 on 2019-05-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='re_auth',
            field=models.TextField(default=''),
        ),
    ]
