# Generated by Django 2.1.7 on 2019-05-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_re_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='auther',
            new_name='author',
        ),
    ]
