# Generated by Django 2.1.7 on 2019-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20190505_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='re_paper',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='tag',
            field=models.CharField(default='big data', max_length=10),
        ),
    ]
