# Generated by Django 2.1.7 on 2019-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20190508_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
